sonar.organization=thiagokwondev
sonar.projectKey=ThiagoKwonDev_site-vicentin-v2
sonar.projectName=vicentin-api

# Código-fonte principal
sonar.sources=src

# Diretório de testes
sonar.tests=src

# Inclusões de arquivos de teste
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts

# Exclusões da análise de qualidade (não conta como código de produção)
sonar.exclusions=**/*.spec.ts,**/*.e2e-spec.ts,dist/**,node_modules/**,coverage/**

# Cobertura de código — gerada pelo Jest (npm run test:ci)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Linguagem TypeScript
sonar.language=ts